name: ephemera

services:
  api:
    build:
      args:
        continueOnTestFailure: true
        workspaceDir: /workspace

      context: .
      dockerfile: api.dockerfile

    command:
      - >-
        mkdir -p /out
        && if [ -n "$( ls -A /out )" ]; then rm -r /out/*; fi
        && cp -r ./dist/* /out
        && node --inspect=0.0.0.0:9229 ./dist/api/main.js

    container_name: ephemera.api

    depends_on:
      - redis

    develop:
      watch:
        # Changes requiring rebuild
        - action: rebuild
          path: ./api
        - action: rebuild
          path: ./data
        - action: rebuild
          path: ./model
        - action: rebuild
          path: ./nx.json
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./package-lock.json
        - action: rebuild
          path: ./provide
        - action: rebuild
          path: ./services
        - action: rebuild
          path: ./stdlib
        - action: rebuild
          path: ./tsconfig.base.json

        # Changes requiring sync & restart
        - action: sync+restart
          path: ./api/config.yaml
          target: /workspace/dist/api/config.yaml
        - action: sync+restart
          path: ./api/config.local.yaml
          target: /workspace/dist/api/config.local.yaml

    ports:
      - 10331:3333
      - 20331:9229

    volumes:
      - ./out:/out

  redis:
    container_name: ephemera.redis

    environment:
      REDIS_ARGS: '--save 30 1 --appendonly yes'

    image: redis/redis-stack-server:latest

    ports:
      - 6379:6379
