name: ephemera

configs:
    api_config:
        file: ./api/config.yaml

    api_config_development:
        file: ./api/config.development.yaml

    api_config_local:
        file: ./api/config.local.yaml

    api_config_production:
        file: ./api/config.production.yaml

services:
    api:
        build:
            args:
                environment: local

            context: .
            dockerfile: api.dockerfile

        command: --inspect=0.0.0.0:9229 /usr/src/dist/api/main.js

        configs:
            - api_config
            - api_local

        container_name: ephemera.api

        depends_on:
            - redis

        develop:
            watch:
                # Changes requiring rebuild
                - action: rebuild
                  path: ./api
                - &rebuild-data
                  action: rebuild
                  path: ./data
                - &rebuild-model
                  action: rebuild
                  path: ./model
                - &rebuild-nx-json
                  action: rebuild
                  path: ./nx.json
                - &rebuild-package-json
                  action: rebuild
                  path: ./package.json
                - &rebuild-package-lock-json
                  action: rebuild
                  path: ./package-lock.json
                - &rebuild-provide
                  action: rebuild
                  path: ./provide
                - &rebuild-services
                  action: rebuild
                  path: ./services
                - &rebuild-stdlib
                  action: rebuild
                  path: ./stdlib
                - &rebuild-tsconfig-base-json
                  action: rebuild
                  path: ./tsconfig.base.json

        environment:
            NODE_ENV: local

        ports:
            - 10331:3333
            - 20331:9229

    redis:
        container_name: ephemera.redis

        environment:
            REDIS_ARGS: '--save 30 1 --appendonly yes'

        image: redis/redis-stack-server:latest

        ports:
            - 6379:6379
