name: nx run
description: Run nx run

inputs:
  arguments:
    description: Arguments to pass to nx run.

runs:
  args:
    - nx
    - run
    - ${{ inputs.arguments }}
  entrypoint: npx
  image: docker.io/node:lts-alpine
  using: docker
