# ================
# preamble
# ================
FROM docker.io/node:lts-alpine AS preamble
VOLUME ["/github/workspace"]
RUN ls -l /var
RUN ls -l /var/lib
RUN ls -l /var/lib/docker
RUN ls -l /var/lib/docker/volumes
COPY ./run.sh .

# ================
# entry
# ================
FROM preamble AS entry
ENTRYPOINT ["./run.sh"]
