# ================
# preamble
# ================
FROM docker.io/node:lts-alpine AS preamble
VOLUME ["/github/workspace"]
RUN ls -l
COPY ./run.sh .

# ================
# entry
# ================
FROM preamble AS entry
ENTRYPOINT ["./run.sh"]
