# ================
# preamble
# ================
FROM docker.io/node:lts-alpine AS preamble
RUN pwd
RUN ls -l
WORKDIR /github/workspace
COPY ./run.sh .
RUN pwd
RUN ls -l

# ================
# entry
# ================
FROM preamble AS entry
ENTRYPOINT ["./run.sh"]
