name: npm install
description: Run npm install

inputs:
  include:
    description: Kinds of dependencies to include.

runs:
  args:
    - ${{ contains(inputs.include, 'dev') && '--include dev'}}
    - ${{ contains(inputs.include, 'optional') && '--include optional'}}
    - ${{ contains(inputs.include, 'peer') && '--include peer'}}
    - ${{ contains(inputs.include, 'prod') && '--include prod'}}
  env:
    WORKING_DIR: ${{ github.workspace }}
  image: dockerfile
  using: docker
