# ================
# preamble
# ================
FROM docker.io/node:lts-alpine AS preamble
RUN mkdir -p /github/workspace
VOLUME ["/github/workspace"]
RUN pwd
RUN ls -l
COPY ./run.sh .

# ================
# entry
# ================
FROM preamble AS entry
ENTRYPOINT ["./run.sh"]
