name: nx run-many
description: Run nx run-many

inputs:
  arguments:
    description: Arguments to pass to nx run-many.

runs:
  args:
    - nx
    - run-many
    - ${{ inputs.arguments }}
  entrypoint: npx
  image: docker.io/node:lts-alpine
  using: docker
