# ================
# preamble
# ================
FROM docker.io/node:lts-alpine AS preamble
VOLUME '/github/workspace'
RUN pwd
RUN ls -l
WORKDIR /github/workspace
COPY ./run.sh .

# ================
# entry
# ================
FROM preamble AS entry
ENTRYPOINT ["./run.sh"]
