name: build-api-official

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build API Docker image
        run: docker build . --build-arg buildTarget=production --build-arg environment=production --file api.dockerfile --tag ephemera.api:$(date +'%Y%m%d')-${{ github.run_number }}

      - name: Export build contents
        run: docker run -v ./out:/out ephemera.api:$(date +'%Y%m%d')-${{ github.run_number }} "./stage.sh"

      - name: Publish unit test results
        if: success() || failure()
        uses: dorny/test-reporter@v1
        with:
          name: Unit tests
          path: out/**/junit.xml
          reporter: jest-junit

      - name: Upload artifact
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-api-official
          path: out

on:
  push:
    branches:
      - main

permissions:
  actions: read
  checks: write
  contents: read
