name: build-api-pr

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build API Docker image
        run: docker build . --build-arg buildTarget=production --build-arg environment=production --file api.dockerfile --tag ephemera.api:$(date +'%Y%m%d')-${{ github.run_number }}

      - name: List images
        run: docker images

      - name: Export build contents
        run: docker run -v ./out:/out ephemera.api:$(date +'%Y%m%d')-${{ github.run_number }} "./stage.sh"

      - name: Check contents
        if: success() || failure()
        run: ls -l

      - name: Publish unit test results
        if: success() || failure()
        uses: dorny/test-reporter@v1
        with:
          name: Unit tests
          path: out/**/junit.xml
          reporter: jest-junit

      - name: Upload artifact
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-api-pr
          path: out
          retention-days: 1

on:
  pull_request:
    branches:
      - main
