name: build-api-pr

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Build API Docker image
        run: docker build . --file api.dockerfile --tag ephemera.api:$(date +%s)

on:
  pull_request:
    branches:
      - main
